#!/bin/bash
#PBS -N GM12878_WT_ChIPseq_WAPL_Proteintech_20230425_B2
#PBS -l nodes=node01:ppn=10
#PBS -l walltime=10000:00:00
#PBS -j n
#PBS -q batch
#PBS -e ${PBS_JOBNAME}.err
#PBS -o ${PBS_JOBNAME}.out

cd $PBS_O_WORKDIR

##############################################
## Tools
bwa=/data/public/software/bwa-0.7.15/bwa
samtools=/data/public/software/samtools-1.3.1/samtools
bedtools=/data/public/software/bedtools.2.25.0/bin/bedtools
MarkDuplicates=/data/public/software/picard-tools-1.107/MarkDuplicates.jar
bedGraphToBigWig=/home/yuhan/Software/others/bin/bedGraphToBigWig

## CPU
cpu_num=10

## input
Genome_Index=/data/public/refGenome/bwa_index/hg38/hg38
chrSize=/data/public/refGenome/bwa_index/hg38/hg38.chrom.sizes

## Options
EXTENSION=250

PREFIX=GM12878_WT_ChIPseq_WAPL_Proteintech_20230425_B2
cd /public2/TangLabData/ProcessedData/ChIP-seq
mkdir ${PREFIX}
cd ${PREFIX}
Fastq_R1=/public2/TangLabData/CleanData/ChIP-seq/${PREFIX}/${PREFIX}_R1.fq.gz
Fastq_R2=/public2/TangLabData/CleanData/ChIP-seq/${PREFIX}/${PREFIX}_R2.fq.gz
## mapping
${bwa} mem -t ${cpu_num} -k 18 -M ${Genome_Index} ${Fastq_R1} ${Fastq_R2} > ${PREFIX}.sam 2>${PREFIX}.bwa.log.txt
${samtools} view -b -o ${PREFIX}.bam -q 20 -@ ${cpu_num} ${PREFIX}.sam 2>${PREFIX}.sam2bam.log.txt

## sort bam by coordinate
${samtools} sort --threads ${cpu_num} -o ${PREFIX}.sorted.bam ${PREFIX}.bam

## delete unsorted bam
rm ${PREFIX}.bam

## remove PCR duplications
java -Xmx40g -jar ${MarkDuplicates} INPUT=${PREFIX}.sorted.bam OUTPUT=${PREFIX}.nodup.bam METRICS_FILE=${PREFIX}.stat.MarkDuplicates.txt REMOVE_DUPLICATES=TRUE ASSUME_SORTED=TRUE VALIDATION_STRINGENCY=SILENT

## read bam convered to bed and calculate coverage
${bedtools} bamtobed -i ${PREFIX}.nodup.bam | awk -v EXTENSIONV=$EXTENSION 'BEGIN{OFS="\t"}{if($NF=="+") print $1,$2,$2+EXTENSIONV;else if($NF=="-"){s=$3-EXTENSIONV;if(s>0) print $1,s,$3;else print $1,0,$3;}}' | grep -v [M_] | LANG=C sort -k1,1 -k2,2n > ${PREFIX}.bed
${bedtools} genomecov -bg -i ${PREFIX}.bed -g ${chrSize} > ${PREFIX}.bedgraph


####################################################################################################################################################
TABLE="/opt/basic/_py/bin/python /opt/basic/console/table_util.py"
TRACK="/opt/basic/_py/bin/python /opt/basic/console/track_util.py"
GENOME="hg38"
FOLDER="GM12878 ChIP-seq"
PREFIX=GM12878_SA2KOA13_SA2201_ChIPseq_SA2Clone61Ab_20230322_B1
File=/public2/TangLabData/ProcessedData/ChIP-seq/${PREFIX}/${PREFIX}.bedgraph

${TABLE} create ${GENOME} -l "${FOLDER}" "${PREFIX}.cov"
num=6251
TABLE_ID=${num}
${TRACK} gen_cov max ${TABLE_ID} ${File}

